### ISSUE TITLE
Allow CORS for AJAX-Requests

### ISSUE THREAD

**Issue by KennethWussmann** [nitrado/Nitrapi#2]
Hey, 
any chance that you add CORS-Support to API-Responses? Without the Response-Header `Access-Control-Allow-Origin` set to `*` (or the used `redirect_uri`) in the responses, I can't do AJAX-Requests from another origin. 

It ends in:

```
XMLHttpRequest cannot load https://oauth.nitrado.net/oauth/v2/token?code=<Code>&client_id=<Client-ID>&client_secret=<Client-Secret>&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%2Fprojects%2FNitradoApp%2F%3Fcallback. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
```

Thanks, 
Kenneth

**Comment by BirknerAlex** [comment]
Thank's for your report.

We will fix it on our oAuth 2.0 server asap.

Regards,
Alexander

**Comment by nitrado-leo** [comment]
Hey,

what exactly are you trying to do? This is by design, if we'd set `Access-Control-Allow-Origin`, you could use it to steal tokens.

Try to set the correct `redirect_uri` in the Nitrado OAuth Client settings. 

Regards,
Leo

**Comment by KennethWussmann** [comment]
Hey, 

I was trying to exchange my `authorization_token` from the API into an `access_token` using an AJAX-Request. eg.:

```JavaScript
var exchangeToken = "https://oauth.nitrado.net/oauth/v2/token?code=<AUTH-CODE>&client_id=<CLIENT-ID>&client_secret=<CLIENT-SECRET>&grant_type=authorization_code&redirect_uri=<REDIRECT-URI>";
$.ajax(exchangeToken, {
    success: function(data, text, xhr) {
        console.log(data);
    }
});
```
But it's not allowed due to the missing `Access-Control-Allow-Origin`.

The `redirect_uri` is correctly set in the settings and in my requests. Otherwise I wouldn't get any `authorization_token`.

I got another solution for the oAuth handshake and WinJS seems to ignore the missing header. Only AJAX in Google Chrome complained about the header.

For me it's solved, but it may be annoying to future developers.

Thanks, 
Kenneth

**Comment by BirknerAlex** [comment]
We've decided to enable CORS in the near future.

I'll update this post once it's enabled and available.

**Comment by BirknerAlex** [comment]
CORS has been implemented and it's live.
