### ISSUE TITLE
Dokumentation und Closed Beta

### ISSUE THREAD

**Issue by ATFBlueshift** [nitrado/Nitrapi#4]
Schönen guten Tag,

ich bin kürzlich auf den Changelog vom 5. November gestoßen.
Da ich momentan eine Anwendung mit der Nitrapi entwickle, wollte ich nur fragen, wann die API aus der Closed Beta geht, da anscheinend einige Punkte in der Dokumentation fehlerhaft, oder noch nicht vorhanden sind.
Gibt es dafür schon ein Datum?

Mit freundlichen Grüßen
Johannes Quast

**Comment by BirknerAlex** [comment]
Hallo,

die Dokumentation wird spätestens nächste Woche aktualisiert. Die wichtigsten Funktionen sind allerdings schon jetzt up-to-date.

Die Beta wurde so eben beendet. 👍 

Liebe Grüße
Alexander

**Comment by JQuastArwed** [comment]
Hallo,

danke für ihre Antwort.
Ich bin schon sehr gespannt auf die finale Version.
Weiterhin möchte ich noch kurz einen Fehler in der Dokumentation melden:
Bei allen Sektionen der "Pricing Info" ist als Parameter "location_id" angegeben.
Dieser Parameter funktioniert nicht, allerings "location" schon.

Mit freundlichen Grüßen
Johannes Quast

**Comment by BirknerAlex** [comment]
Tatsächlich, der Parameter location= ist korrekt.
Werden wir natürlich auch ausbessern, danke.

**Comment by BirknerAlex** [comment]
Hallo,

der Location Parameter wurde nun in der Dokumentation angepasst.

Liebe Grüße
Alexander
