### ISSUE TITLE
OAuth Token Request nicht möglich

### ISSUE THREAD

**Issue by TheLegendaryMarc** [nitrado/Nitrapi#5]
Wenn man wie in der Dokumentation beschreiben ist einen Auth Request gesendet hat und dann einen Token Request startet erscheint immer die Fehlermeldung "Client Secret is not valid!" obwohl der Client Secret dabei und richtig ist.

Request:
![image](https://cloud.githubusercontent.com/assets/11300323/25564562/440fdf50-2db6-11e7-82b1-042417ea77e9.png)

Response:
![image](https://cloud.githubusercontent.com/assets/11300323/25564566/579d0cbe-2db6-11e7-872b-f26bc6945971.png)

Nebenbei wieso steht in der Doku das man einen POST Request auf "https://api.nitrado.net/oauth/v2/token" machen soll aber der nur ein 404 Code wirft ?

**Comment by BirknerAlex** [comment]
Hi! 

Es gibt wohl anscheinend ein Problem beim anlegen der Anwendungen über unsere Webseite. Ich werde voraussichtlich morgen dafür einen Fix veröffentlichen. Heute komm ich vermutlich nicht mehr dazu. 

Die Token URL lautet anders als leider noch in der Dokumentation steht wie folgt https://oauth.nitrado.net/oauth/v2/token. Das werde ich auch morgen direkt beheben.

Liebe Grüße
Alexander

**Comment by BirknerAlex** [comment]
Kurzes Update, das Problem konnte ich finden und beheben. Die Änderung ist aktuell im Review Prozess und wenn alles gut läuft, geht der Fix morgen online.

Den Fehler in der Dokumentation habe ich auch behoben und das ist auch schon live.

**Comment by BirknerAlex** [comment]
Hi!

Der Fehler wurde behoben. Du kannst im "Entwickler-Portal" den Secret deiner App zurücksetzen. Danach sollte alles funktionieren.

Bitte um Rückmeldung ob der Fehler behoben ist.

Liebe Grüße
Alexander

**Comment by TheLegendaryMarc** [comment]
Hey Alex,

vielen Dank für deine Hilfe, habe es gerade nochmal geprüft und es funktioniert einwandfrei.

200 OK :)

Grüße Marc
