### ISSUE TITLE
Can not make game server, access ftp, reinstall game, or switch.

### ISSUE THREAD

**Issue by TMFuzz** [nitrado/NitrAPI#7]
`Unhandled exception during event run: "Wrong owner: root Correct owner: ni1312013_1 Path: /games/ni1312013_1/ftproot" Traceback (most recent call last): File "nitrapi_daemon/main.py", line 574, in publish_result_callback File "concurrent/futures/_base.py", line 398, in result File "concurrent/futures/_base.py", line 357, in __get_result File "concurrent/futures/thread.py", line 55, in run File "nitrapi_daemon/main.py", line 544, in process_request_worker File "events/base.py", line 73, in run_event File "events/base.py", line 41, in run_event File "events/services/gameservers/fileserver/mkdir.py", line 24, in run File "events/base.py", line 107, in acl_directory File "events/base.py", line 77, in _acl_path File "utils/fs_security.py", line 117, in acl_user_for_directory File "utils/fs_security.py", line 86, in _acl_user_for_path RuntimeError: Wrong owner: root Correct owner: ni1312013_1 Path: /games/ni1312013_1/ftproot`

The site is broken and I cant make the server I just paid for.

**Comment by NitradoTimo** [comment]
Please raise an issue here https://support.nitrado.net/
